# Generated by Django 5.2.17 on 2026-09-22 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('object_type', models.CharField(default='season', max_length=32, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID объекта')),
                ('object_label', models.CharField(blank=True, max_length=200, verbose_name='Объект')),
                ('tab', models.CharField(choices=[('meta', 'Мета'), ('zadachi', 'Задачи'), ('rezultaty', 'Результаты'), ('iypt', 'IYPT'), ('foto', 'Фото'), ('materialy', 'Материалы'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Раздел')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('publish', 'Публикация'), ('enable_section', 'Включение раздела'), ('delete', 'Удаление'), ('make_current', 'Сделать текущим'), ('archive_current', 'В прошедшие')], max_length=32, verbose_name='Действие')),
                ('summary', models.CharField(max_length=400, verbose_name='Кратко')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Снимок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал правок',
                'ordering': ['-created_at'],
            },
        ),
    ]
