# Generated by Django 5.2.17 on 2026-09-18 07:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(verbose_name='Текст страницы')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата')),
                ('body', wagtail.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Коротко о турнире'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lead',
            field=models.CharField(blank=True, help_text='Одно предложение под названием. Его видно первым на сайте.', max_length=240, verbose_name='Главная фраза'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='opponent_text',
            field=models.TextField(blank=True, verbose_name='Оппонент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reporter_text',
            field=models.TextField(blank=True, verbose_name='Докладчик'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviewer_text',
            field=models.TextField(blank=True, verbose_name='Рецензент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='season_label',
            field=models.CharField(blank=True, help_text='Например: 2025/26', max_length=80, verbose_name='Сезон'),
        ),
    ]
