# Generated by Django 5.2.17 on 2026-09-18 08:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contentpage_newsindexpage_newspage_homepage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Текст страницы'),
        ),
    ]
