# Generated by Django 5.2.17 on 2026-09-18 10:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contentpage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TournamentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('roman', models.CharField(blank=True, max_length=16, verbose_name='Римский номер')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий сезон')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Конец')),
                ('iypt_team', models.TextField(blank=True, verbose_name='Кто поехал на IYPT')),
                ('results_more_url', models.URLField(blank=True, verbose_name='Подробные результаты, ссылка')),
                ('results_more_label', models.CharField(blank=True, default='Подробнее', max_length=160, verbose_name='Подпись к ссылке на результаты')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TournamentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('news', 'Новость'), ('report', 'Отчёт')], default='news', max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.tournamentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.tournamentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('statement', models.TextField(verbose_name='Условие')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='home.tournamentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentResultRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('place', models.CharField(max_length=16, verbose_name='Место')),
                ('team', models.CharField(max_length=200, verbose_name='Команда')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('points', models.CharField(blank=True, max_length=32, verbose_name='Сумма')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='home.tournamentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
