# Generated by Django 5.2.17 on 2026-09-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_tournamentindexpage_tournamentpage_tournamentlink_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentpage",
            name="photo_album_url",
            field=models.URLField(
                blank=True,
                help_text="Например альбом ВК. Файлы на сервер не копируются.",
                verbose_name="Альбом фото (ссылка, не файл)",
            ),
        ),
        migrations.AddField(
            model_name="tournamentphoto",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на фото"),
        ),
        migrations.AlterField(
            model_name="tournamentphoto",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Файл на сервере",
            ),
        ),
    ]
