# Generated by Django 5.2.17 on 2026-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_result_row_league_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpage',
            name='iypt_more_label',
            field=models.CharField(blank=True, default='Оригинал', max_length=160, verbose_name='Подпись к ссылке на IYPT'),
        ),
        migrations.AddField(
            model_name='tournamentpage',
            name='iypt_more_url',
            field=models.URLField(blank=True, verbose_name='Подробные результаты IYPT, ссылка'),
        ),
        migrations.AlterField(
            model_name='tournamentresultrow',
            name='kind',
            field=models.CharField(choices=[('ranking', 'Общий рейтинг'), ('league_a', 'Высшая лига'), ('league_b', 'Первая лига'), ('final', 'Финал высшей лиги'), ('final_b', 'Финал первой лиги'), ('iypt_ranking', 'IYPT: рейтинг'), ('iypt_final', 'IYPT: финал')], default='ranking', max_length=16, verbose_name='Таблица'),
        ),
    ]
