# Generated by Django 5.2.17 on 2026-09-22 09:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_problem_scans'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('region_code', models.CharField(choices=[('RU-ALT', 'Алтайский край'), ('RU-AMU', 'Амурская область'), ('RU-ARK', 'Архангельская область'), ('RU-AST', 'Астраханская область'), ('RU-BEL', 'Белгородская область'), ('RU-BRY', 'Брянская область'), ('RU-VLA', 'Владимирская область'), ('RU-VGG', 'Волгоградская область'), ('RU-VLG', 'Вологодская область'), ('RU-VOR', 'Воронежская область'), ('RU-YEV', 'Еврейская автономная область'), ('RU-ZAB', 'Забайкальский край'), ('RU-IVA', 'Ивановская область'), ('RU-IRK', 'Иркутская область'), ('RU-KB', 'Кабардино-Балкарская Республика'), ('RU-KGD', 'Калининградская область'), ('RU-KLU', 'Калужская область'), ('RU-KAM', 'Камчатский край'), ('RU-KC', 'Карачаево-Черкесская Республика'), ('RU-KEM', 'Кемеровская область'), ('RU-KIR', 'Кировская область'), ('RU-KOS', 'Костромская область'), ('RU-KDA', 'Краснодарский край'), ('RU-KYA', 'Красноярский край'), ('RU-KGN', 'Курганская область'), ('RU-KRS', 'Курская область'), ('RU-LEN', 'Ленинградская область'), ('RU-LIP', 'Липецкая область'), ('RU-MAG', 'Магаданская область'), ('RU-MOW', 'Москва'), ('RU-MOS', 'Московская область'), ('RU-MUR', 'Мурманская область'), ('RU-NEN', 'Ненецкий автономный округ'), ('RU-NIZ', 'Нижегородская область'), ('RU-NGR', 'Новгородская область'), ('RU-NVS', 'Новосибирская область'), ('RU-OMS', 'Омская область'), ('RU-ORE', 'Оренбургская область'), ('RU-ORL', 'Орловская область'), ('RU-PNZ', 'Пензенская область'), ('RU-PER', 'Пермский край'), ('RU-PRI', 'Приморский край'), ('RU-PSK', 'Псковская область'), ('RU-AD', 'Республика Адыгея (Адыгея)'), ('RU-AL', 'Республика Алтай'), ('RU-BA', 'Республика Башкортостан'), ('RU-BU', 'Республика Бурятия'), ('RU-DA', 'Республика Дагестан'), ('RU-IN', 'Республика Ингушетия'), ('RU-KL', 'Республика Калмыкия'), ('RU-KR', 'Республика Карелия'), ('RU-KO', 'Республика Коми'), ('RU-CR', 'Республика Крым'), ('RU-ME', 'Республика Марий Эл'), ('RU-MO', 'Республика Мордовия'), ('RU-SA', 'Республика Саха (Якутия)'), ('RU-SE', 'Республика Северная Осетия — Алания'), ('RU-TA', 'Республика Татарстан (Татарстан)'), ('RU-TY', 'Республика Тыва'), ('RU-KK', 'Республика Хакасия'), ('RU-ROS', 'Ростовская область'), ('RU-RYA', 'Рязанская область'), ('RU-SAM', 'Самарская область'), ('RU-SPE', 'Санкт-Петербург'), ('RU-SAR', 'Саратовская область'), ('RU-SAK', 'Сахалинская область'), ('RU-SVE', 'Свердловская область'), ('RU-SMO', 'Смоленская область'), ('RU-STA', 'Ставропольский край'), ('RU-TAM', 'Тамбовская область'), ('RU-TVE', 'Тверская область'), ('RU-TOM', 'Томская область'), ('RU-TUL', 'Тульская область'), ('RU-TYU', 'Тюменская область'), ('RU-UD', 'Удмуртская Республика'), ('RU-ULY', 'Ульяновская область'), ('RU-KHA', 'Хабаровский край'), ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра'), ('RU-CHE', 'Челябинская область'), ('RU-CE', 'Чеченская Республика'), ('RU-CU', 'Чувашская Республика — Чувашия'), ('RU-CHU', 'Чукотский автономный округ'), ('RU-YAN', 'Ямало-Ненецкий автономный округ'), ('RU-YAR', 'Ярославская область'), ('RU-SEV', 'Севастополь')], db_index=True, max_length=16, verbose_name='Субъект РФ')),
                ('has_tournament', models.BooleanField(default=True, verbose_name='Есть турнир (подсветка на карте)')),
                ('title', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('city', models.CharField(blank=True, max_length=160, verbose_name='Город / площадка')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Конец')),
                ('date_note', models.CharField(blank=True, help_text='Например: «март 2026» или «даты уточняются».', max_length=200, verbose_name='Когда (свободная формулировка)')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('info', wagtail.fields.RichTextField(blank=True, verbose_name='О турнире')),
                ('results_url', models.CharField(blank=True, max_length=500, verbose_name='Результаты: ссылка на оригинал')),
                ('results_label', models.CharField(blank=True, default='Оригинал результатов', max_length=160, verbose_name='Подпись к результатам')),
                ('results_text', models.TextField(blank=True, help_text='Можно списком: место — команда.', verbose_name='Краткие результаты')),
            ],
            options={
                'verbose_name': 'Региональный турнир',
                'verbose_name_plural': 'Региональные турниры',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussiaTournamentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Короткий текст над картой.', verbose_name='Вступление')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RegionalProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('statement', models.TextField(blank=True, verbose_name='Условие')),
                ('tournament', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='home.regionaltournament')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('external_url', models.TextField(blank=True, verbose_name='Или внешняя ссылка')),
                ('original_url', models.URLField(blank=True, verbose_name='Оригинал')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Файл')),
                ('tournament', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.regionaltournament')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='regionaltournament',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='home.russiatournamentspage'),
        ),
        migrations.AlterUniqueTogether(
            name='regionaltournament',
            unique_together={('page', 'region_code')},
        ),
    ]
